apiVersion: v1
kind: Pod
metadata:
  name: nginx-ex
  labels:
    app: nginx-ex
spec:
  containers:
    - name: server
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
