apiVersion: v1
kind: Pod
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  containers:
    - name: server
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  labels:
    app: nginx-example
spec:
  selector:
    app: nginx-example
  ports:
    - port: 80
      protocol: TCP
  type: LoadBalancer
